server:
  port: 8010

spring:
  application:
    name: wanghh-redis
  redis:
    database: 0
    host: 47.93.215.92
    port: 6379
    password:
    jedis:
      pool:
        max-active: 100
        max-idle: 3
        max-wait: -1
        min-idle: 0
    timeout: 1000
