server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true # 开启从注册中心动态创建路由的功能,利用微服务名进行路由
      routes:
        - id: payment_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          #uri: http://localhost:8001  #匹配后提供服务的路由地址
          uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由
            #- After=2021-03-18T22:40:58.935+08:00[Asia/Shanghai] #在次时间之后才可访问
            #- Before=2021-03-18T22:40:58.935+08:00[Asia/Shanghai] #在次时间之前才可访问
            #- Between=2017-01-20T17:42:47.789-07:00[Asia/Shanghai], 2017-01-21T17:42:47.789-07:00[Asia/Shanghai] #在次时间段内可以访问
            #- Cookie=username,wanghh #带cookie才可访问 curl http://localhost:9527/payment/lb --cookie "username=wanghh"
            #- Header=X-Request-Id, \d+ #请求头带指定的参数才可访问 curl http://localhost:9527/payment/lb -H "username:wanghh"
            #- Host=**.haha.com,**.anotherhost.org # 匹配才可访问 curl http://localhost:9527/payment/lb -H "Host:www.haha.com"
            - Method=GET,POST # 请求必须是get 或post才可访问

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
    instance-id: gateway9527 # eureka主机名称
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，默认为true 单节点无所谓 集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

