server:
  port: 9527

spring:
  application:
    name: cloud-gateway
  cloud:
    gateway:
      routes:
        - id: payment_routh #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址 没有进行负载均衡
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/get/** #断言，路径相匹配的进行路由

        - id: payment_routh2 #payment_routh #路由的ID，没有固定规则，但要求唯一，建议配合服务名
          uri: http://localhost:8001  #匹配后提供服务的路由地址
          #uri: lb://cloud-payment-service #匹配后提供服务的路由地址
          predicates:
            - Path=/payment/lb/** #断言，路径相匹配的进行路由

eureka:
  instance:
    hostname: eureka7001.com #eureka服务端的实例名称
    instance-id: gateway9527 # eureka主机名称
  client:
    #表示是否将自己注册进eureka server 默认为true
    register-with-eureka: true
    #是否从eureka server抓取已有的注册信息，默认为true 单节点无所谓 集群必须设置为true 才能配合ribbon使用负载均衡
    fetch-registry: true
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

